### ISSUE TITLE
Remote Databases Setup with Test Data

### ISSUE THREAD

**Issue by tomjmartinez** [KeithSantamaria/CHOGAN#11]
You're responsible for:

- [ ] create 2 separate remote mongodb databases using Atlas

- [ ] One called "chogan-projects" the other called "chogan-users"

- [ ] Add Collection "projects" to the projects database

- [ ] Add Collections "users" and "tags" to the users database

- [ ] add some sample data that follows the class models diagram provide inside 'documentation' folder

- [ ] Connect the databases to the backed by adding the mongodb uri field into the respective backend Spring application.properties files

**Comment by KeithSantamaria** [comment]
oo I like the checklist you did for this issue !

how did you do that in the markdown?

**Comment by tomjmartinez** [comment]
- [ ]  "- [ ]"

**Comment by KeithSantamaria** [comment]
@toledojuan @KAltieri Got this working! GJ
