### ISSUE TITLE
Make sure services run on different ports

### ISSUE THREAD

**Issue by KeithSantamaria** [KeithSantamaria/CHOGAN#9]
The only one service can run a port, so the other fail when running. 

Change one service to port 6969

and another to 42069

**Comment by scbarnard** [comment]
Ports for discovery service, messaging queue, and gateway?

**Comment by KeithSantamaria** [comment]
> Ports for discovery service, messaging queue, and gateway?

The ports for the gateway, the authentication, and the project services. 

We have not added messaging or discovery functionality yet

**Comment by KeithSantamaria** [comment]
Well I pulled a big dumb dumb and accidently pushed it to the main branch... It shouldnt cause any bugs, but to rectify I added more rules on main branch protections
